# Generated by Django 4.0.5 on 2022-07-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_personales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=3)),
                ('domicilio', models.TextField(max_length=255)),
                ('tel', models.IntegerField(verbose_name=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
